config/routes.rb
Rails.application.routes.draw do
  resources :widget_homes
  resources :widgets
  resources :homes
  devise_for :models
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  belongs_to :model

  has_many :widget_home
  has_many :widgets, :through => :widget_home

end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :home
end

app/models/widget.rb
class Widget < ApplicationRecord
end

app/models/widget_home.rb
class WidgetHome < ApplicationRecord
  belongs_to :widget
  belongs_to :home
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_model!
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:model_id, :nome)
    end
end

app/controllers/widget_homes_controller.rb
class WidgetHomesController < ApplicationController
  before_action :set_widget_home, only: [:show, :edit, :update, :destroy]

  # GET /widget_homes
  # GET /widget_homes.json
  def index
    @widget_homes = WidgetHome.all
  end

  # GET /widget_homes/1
  # GET /widget_homes/1.json
  def show
  end

  # GET /widget_homes/new
  def new
    @widget_home = WidgetHome.new
  end

  # GET /widget_homes/1/edit
  def edit
  end

  # POST /widget_homes
  # POST /widget_homes.json
  def create
    @widget_home = WidgetHome.new(widget_home_params)

    respond_to do |format|
      if @widget_home.save
        format.html { redirect_to @widget_home, notice: 'Widget home was successfully created.' }
        format.json { render :show, status: :created, location: @widget_home }
      else
        format.html { render :new }
        format.json { render json: @widget_home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widget_homes/1
  # PATCH/PUT /widget_homes/1.json
  def update
    respond_to do |format|
      if @widget_home.update(widget_home_params)
        format.html { redirect_to @widget_home, notice: 'Widget home was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget_home }
      else
        format.html { render :edit }
        format.json { render json: @widget_home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widget_homes/1
  # DELETE /widget_homes/1.json
  def destroy
    @widget_home.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Widget home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget_home
      @widget_home = WidgetHome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_home_params
      params.require(:widget_home).permit(:width, :height, :background_color, :widget_id, :home_id)
    end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/widget_homes_helper.rb
module WidgetHomesHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :model_id, id: :home_model_id, value: current_model.id %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :home_nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homes</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.model %></td>
        <td><%= home.nome %></td>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @home.model %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @home.nome %>
</p>

<div class="row">
  <% @home.widget_home.each do |widget_home| %>
    <%= render partial: "widgets/widget", locals: { widget_home: widget_home, width: widget_home.width, color: widget_home.background_color, widget: widget_home.widget.nome.downcase } %>
  <% end %>
</div>


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/widget_homes/_form.html.erb
<%= form_with(model: widget_home, local: true) do |form| %>
  <% if widget_home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(widget_home.errors.count, "error") %> prohibited this widget_home from being saved:</h2>

      <ul>
      <% widget_home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :width %>
    <%= form.number_field :width, id: :widget_home_width %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height, id: :widget_home_height %>
  </div>

  <div class="field">
    <%= form.label :background_color %>
    <%= form.text_field :background_color, id: :widget_home_background_color %>
  </div>

  <div class="field">
    <%= form.label :widget_id %>
    <%= form.text_field :widget_id, id: :widget_home_widget_id %>
  </div>

  <div class="field">
    <%= form.label :home_id %>
    <%= form.text_field :home_id, id: :widget_home_home_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/widget_homes/edit.html.erb
<h1>Editing Widget_home</h1>

<%= render 'form', widget_home: @widget_home %>

<%= link_to 'Show', @widget_home %> |
<%= link_to 'Back', widget_homes_path %>

app/views/widget_homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Widget_homes</h1>

<table>
  <thead>
    <tr>
      <th>Width</th>
      <th>Height</th>
      <th>Widget</th>
      <th>Home</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widget_homes.each do |widget_home| %>
      <tr>
        <td><%= widget_home.width %></td>
        <td><%= widget_home.height %></td>
        <td><%= widget_home.widget %></td>
        <td><%= widget_home.home %></td>
        <td><%= link_to 'Show', widget_home %></td>
        <td><%= link_to 'Edit', edit_widget_home_path(widget_home) %></td>
        <td><%= link_to 'Destroy', widget_home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget_home', new_widget_home_path %>

app/views/widget_homes/new.html.erb
<h1>New Widget_home</h1>

<%= render 'form', widget_home: @widget_home %>

<%= link_to 'Back', widget_homes_path %>

app/views/widget_homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Width:</strong>
  <%= @widget_home.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @widget_home.height %>
</p>

<p>
  <strong>Widget:</strong>
  <%= @widget_home.widget %>
</p>

<p>
  <strong>Home:</strong>
  <%= @widget_home.home %>
</p>

<%= link_to 'Edit', edit_widget_home_path(@widget_home) %> |
<%= link_to 'Back', widget_homes_path %>

app/views/widgets/_clientes.html.erb
<h3>Clientes</h3>

<p>Widget que deve conter dados de clientes da LSoluções.</p>

app/views/widgets/_financeiro.html.erb
<h3>Financeiro</h3>

<p>Widget que deve conter dados financeiros da LSoluções.</p>

app/views/widgets/_form.html.erb
<%= form_with(model: widget, local: true) do |form| %>
  <% if widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :widget_nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/widgets/_ordem_servico.html.erb
<h3>Ordens de serviço</h3>

<%= month_calendar do |date| %>
  <%= date %>
<% end %>

app/views/widgets/_teste.html.erb
<h3>Teste</h3>

<p>Teste de widget para o projeto que eu estou desenvolvendo para a LSoluções.</p>

app/views/widgets/_widget.html.erb
<div class="col s<%= width %>">
  <div class="widget  <%= color %>" style="color: <%= color %>">
    <%= link_to widget_home, method: :delete, data: { confirm: 'Are you sure?' }, class: "close-btn right" do %>
      &#10006;
    <% end %>

    <header class="<%= color %>">
      <center>
        <h3>

        </h3>
      </center>
    </header>

    <%= render partial: "widgets/#{widget}" %>

  </div>

</div>

app/views/widgets/edit.html.erb
<h1>Editing Widget</h1>

<%= render 'form', widget: @widget %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Widgets</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.nome %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New Widget</h1>

<%= render 'form', widget: @widget %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @widget.nome %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>